data:
    raw_path: "data/raw/"
    processed_path: "data/processed/"
    test_size: 0.2
    random_state: 42

model:
    available_model: ["ridge", "lasso", "random_forest", "xgboost", "lightgbm", "mlp", "image_classifier"]
    model_path: "data/models/"
    model_type: "image_classifier"

api:
    host: "0.0.0.0"
    # nom docker host
    dockerhost: "ml_service"
    port: 8000
    debug: false

front:
    title: "Application ML"
    version: "1.0.0"
    url: "http://localhost:8501"

server:
    title: "Serveur Application ML"
    version: "1.0.0"

logging:
    show_time: true
    show_level: true
